entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: cray@cloudrangerops.net
      storage: acme.json
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
http:
  routers:
    nginx-router:
      rule: "Host(`defectdojo.secops-ba.win`)"
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver
      service: nginx-service
 
  services:
    nginx-service:
      loadBalancer:
        servers:
          - url: "http://172.28.0.9:8090"

providers:
  docker:
    exposedByDefault: false
